server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  error:
    whitelabel:
      enabled: false
    path: /error

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/api/inventory
        - id: product-service-books
          uri: lb://product-service
          predicates:
            - Path=/api/books/**
        - id: product-service-authors
          uri: lb://product-service
          predicates:
            - Path=/api/authors/**
logging:
  level:
    root: INFO
  file:
    path: .logs/gateway-service
    name: ${logging.file.path}/log.log
    max-history: 0
  pattern:
    file: "%d{dd-MM-yyyy HH:mm:ss.SSS} [%thread] %-5level %logger{36}.%M - %msg%n"
    console: "%d{dd-MM-yyyy HH:mm:ss.SSS} %magenta([%thread]) %highlight(%-5level) %logger.%M - %msg%n"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka