server:
  port: 8761
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  error:
    whitelabel:
      enabled: false
    path: /error
logging:
  level:
    root: INFO
  file:
    path: .logs/discovery-service
    name: ${logging.file.path}/log.log
    max-history: 0
  pattern:
    file: "%d{dd-MM-yyyy HH:mm:ss.SSS} [%thread] %-5level %logger{36}.%M - %msg%n"
    console: "%d{dd-MM-yyyy HH:mm:ss.SSS} %magenta([%thread]) %highlight(%-5level) %logger.%M - %msg%n"
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka